version: '3'
services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/usr/src/app/cube
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
